version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  docs-deploy:
    working_directory: ~/repo
    docker:
      - image: node:11.12.0
    steps:
      - checkout
      - run:
          name: Install and configure dependencies
          command: |
            yarn global add gh-pages
            git config user.email "contact@duncte123.me"
            git config user.name "duncte123"
      - run:
          name: Deploy docs to gh-pages branch
          command: yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: dunctebot
